name: Deploy to Staging (Hostinger)

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy theme to Hostinger (staging)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: 92.112.191.78
          username: u772682663
          port: 65002
          protocol: sftp
          ssh-private-key: ${{ secrets.SSH_KEY }}
          local-dir: ./
          server-dir: /domains/stg.falconbodies.com/public_html/wp-content/themes/molla-child/
